study/Django项目/班级管理后台/app/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from rest_framework.routers import SimpleRouter
from app import views

router = SimpleRouter()

router.register(r'^api/student',views.api_student)
router.register(r'^api/grade',views.api_grade)


urlpatterns = [
    # 应用首页
    url(r'^index/', views.index, name='index'),
    url(r'^head/', views.head, name='head'),
    # 应用侧栏
    url(r'^left/', views.left, name='left'),
    # 显示班级列表
    url(r'^grade/', views.grade, name='grade'),
    # 添加班级
    url(r'^addgrade/', views.addgrade, name='addgrade'),
    # 添加学生
    url(r'^addstu/', views.addstu, name='addstu'),
    # 显示学生列表
    url(r'^student/', views.students, name='student'),
    # 删除学生
    url(r'^delete/', views.delete, name='delete'),
    # 更新班级信息方式一使用这个  前段页面要设置
    # url(r'^updategrade/',views.updategrade,name='updategrade'),
    url(r'^editorstudent/', views.editorstudent, name='editorstudent'),

    #F/Q的使用
    url(r'selectstuden/',views.selectstuden),
    url(r'selectstu/',views.selectstu),

    url(r'editorg/',views.editorg)
]
urlpatterns +=router.urls

#django自带的用户验证
# urlpatterns = [
#     # 应用首页
#     url(r'^index/', login_required(views.index), name='index'),
#     url(r'^head/', login_required(views.head), name='head'),
#     # 应用侧栏
#     url(r'^left/', login_required(views.left), name='left'),
#     # 显示班级列表
#     url(r'^grade/', login_required(views.grade), name='grade'),
#     # 添加班级
#     url(r'^addgrade/', login_required(views.addgrade), name='addgrade'),
#     # 添加学生
#     url(r'^addstu/', login_required(views.addstu), name='addstu'),
#     # 显示学生列表
#     url(r'^student/', login_required(views.students), name='student'),
#     # 删除学生
#     url(r'^delete/', login_required(views.delete), name='delete'),
#     # 更新班级信息方式一使用这个  前段页面要设置
#     # url(r'^updategrade/',views.updategrade,name='updategrade'),
#     url(r'^editorstudent/', login_required(views.editorstudent), name='editorstudent'),
#
#
# ]

study/Django项目/班级管理后台/day10/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from day10.settings import MEDIA_URL, MEDIA_ROOT


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 导入应用的中的url
    url(r'^app/',include('app.urls',namespace ='app')),
    url(r'^user/',include('user.urls',namespace='user')),

]

# 把media做成静态目录
urlpatterns += static(MEDIA_URL,document_root = MEDIA_ROOT)

study/Django项目/班级管理后台/user/urls.py
from django.conf.urls import url

from user import views

urlpatterns = [
    # # 注册
    # url(r'^register/', views.register, name='djregister'),
    # # 登录
    # url(r'^login/', views.login, name='djlogin'),
    # url(r'^logout/', views.logout, name='djlogout'),

    # 自己实现注册
    url(r'^register/', views.register, name='register'),
    # 登录
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    # 权限
    url(r'userper/',views.userper,name='userper'),

]

study/Django项目/班级管理后台/templates/addgrade.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="generator" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>

    <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
</head>

<body>
<!-- Popup -->
<div id="Popup">

    <!-- SubPopup -->
    <div id="SubPopup">
        <script type="text/javascript">
            $(function () {
                $(".select").each(function () {
                    var s = $(this);
                    var z = parseInt(s.css("z-index"));
                    var dt = $(this).children("dt");
                    var dd = $(this).children("dd");
                    var _show = function () {
                        dd.slideDown(200);
                        dt.addClass("cur");
                        s.css("z-index", z + 1);
                    };
                    var _hide = function () {
                        dd.slideUp(200);
                        dt.removeClass("cur");
                        s.css("z-index", z);
                    };
                    dt.click(function () {
                        dd.is(":hidden") ? _show() : _hide();
                    });
                    dd.find("a").click(function () {
                        dt.html($(this).html());
                        _hide();
                    });
                    $("body").click(function (i) {
                        !$(i.target).parents(".select").first().is(s) ? _hide() : "";
                    });
                })
            })
            $(document).ready(function () {
                var path = location.href
                grade_id =path.split('=')[1]
                $.get('/app/api/grade/'+grade_id +'/',function (msg) {
                    $('#grade_name').val(msg.data.g_name);
                })
            });
            function editgrade() {
                var path = location.href
                grade_id =path.split('=')[1]
                var csrf ='csfrmiddlewaretoken'
                $.ajax({
                    url:'/app/api/grade/'+grade_id +'/',
                    type:'PATCH',
                    dataType:'json',
                    data :{'g_name':$('#grade_name').val()},
                    headers:{'X-CSRFToken':csrf},
                    success: function () {
                        location.href = '/app/grade/';
                    },
                    error:function (msg) {
                        alert('失败')
                    }

                });
            }





        </script>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form_boxC">
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        <th width="100">班级名称</th>
                        <td>
                            <div class="selectbox" style="width:230px;">
                                <input type="text" name="grade_name" value="" id="grade_name" placeholder="请填入班级名称">
                            </div>
                        </td>
                    </tr>

                </table>
                <div id="BtmBtn">
                    <div class="btn_box floatR">
                        <input name="" type="" onclick="editgrade();"  value="提交">
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- SubPopup -->


</div>
<!-- /Popup -->
</body>
</html>

study/Django项目/班级管理后台/templates/addstu.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="generator" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>

</head>

<body>
<!-- Popup -->
<div id="Popup">

    <!-- SubPopup -->
    <div id="SubPopup">
        <script type="text/javascript">
            $(function () {
                $(".select").each(function () {
                    var s = $(this);
                    var z = parseInt(s.css("z-index"));
                    var dt = $(this).children("dt");
                    var dd = $(this).children("dd");
                    var _show = function () {
                        dd.slideDown(200);
                        dt.addClass("cur");
                        s.css("z-index", z + 1);
                    };
                    var _hide = function () {
                        dd.slideUp(200);
                        dt.removeClass("cur");
                        s.css("z-index", z);
                    };
                    dt.click(function () {
                        dd.is(":hidden") ? _show() : _hide();
                    });
                    dd.find("a").click(function () {
                        dt.html($(this).html());
                        _hide();
                    });
                    $("body").click(function (i) {
                        !$(i.target).parents(".select").first().is(s) ? _hide() : "";
                    });
                })
            })
        </script>
        <div class="form_boxC">
            <p>"<span class="f_cB">*</span>"号为必填项目</p>
            <form action="{% url 'app:addstu' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        <th>员工姓名 <span class="f_cB">*</span></th>
                        <td>
                            <div class="txtbox floatL" style="width:150px;">
                                <input name="s_name" type="text" size="10" value="" placeholder="请输入姓名"></div>
                        </td>
                    </tr>

                     <tr>
                            <th>头像 <span class="f_cB">*</span></th>
                            <td>
                                <div class="txtbox floatL" style="width:150px;">
                                    <input name="s_img" type="file" size="10" ">
                                </div>
                            </td>
                        </tr>

                    <tr>
                        <th>所属班级<span class="f_cB">*</span></th>
                        <td><!-- selectbox -->
                            <select name="g_id" id="">
                                {% for grade in grades %}
                                {# value = grade.id去选项的值#}
                                <option value="{{ grade.id }}">{{ grade.g_name }}</option>
                                {% endfor %}
                        </td>
                    </tr>

                </table>
                <div id="BtmBtn">
                    <div class="btn_box floatR"><input name="" type="submit" value="提交"></div>
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

study/Django项目/班级管理后台/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}
            {% endblock %}
        </title>
        {% block extCSS %}
        {% endblock %}
        {% block extJS %}
        {% endblock %}
    </head>
    {% block indexbody %}
    {% endblock %}
    <body>
    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
    </body>
</html>

study/Django项目/班级管理后台/templates/base_main.html
{% extends 'base.html' %}

{% block extJS %}
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
{% endblock %}

study/Django项目/班级管理后台/templates/grade.html
{% extends 'base_main.html' %}

{% block extCSS %}
    <link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>
{% endblock %}

{% block extJS %}
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $.get('/app/api/grade/',function (msg) {
                var tr_html_all = '';
                for (var i = 0; i < msg.data.results.length; i +=1){
                    var html = '';
                    html += '<tr>'
                    html += '<td>' + msg.data.results[i].id + '</td>'
                    html += '<td>' + msg.data.results[i].g_name + '</td>'
                    html += '<td>' + msg.data.results[i].g_create_time  + '</td>'
                    html += '<td><a href="/app/editorg/?grade_id='+ msg.data.results[i].id +'">编辑</a></td>'
                    tr_html_all += html
                }
                $('#grade_list').append(tr_html_all)
            });
        });




    </script>
{% endblock %}

{% block indexbody %}
    <!-- MainForm -->
<div id="MainForm">
    <div class="form_boxA" id='div_add'>
        <h2>班级信息列表</h2>
        {% csrf_token %}
        <table cellpadding="0" cellspacing="0" id="grade_list">
            <tr>
                <th>序号</th>
                <th>班级名称</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>


        </table>
        <p class="msg">共找到{{ total }}个班级记录</p>
    </div >

    <ul id="PageNum">

        <li><a href="{% url 'app:grade' %}">首页</a></li>
        {% if pages.has_previous %}
        <li><a href="{% url 'app:grade' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>
        {% endif %}
        {% for i in  pages.paginator.page_range %}
        <li><a href="{% url 'app:grade' %}?page_num={{ i }}">{{ i }}</a></li>
        {% endfor %}
        {% if pages.has_next %}
        <li><a href="{% url 'app:grade' %}?page_num={{ pages.next_page_number }}">下一页</a></li>
        {% endif %}
        <li>当前{{ pages.number }}页</li>
        <li><a href="{% url 'app:grade' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
    </ul>

</div>

{% endblock %}

study/Django项目/班级管理后台/templates/grade2.html
{% extends 'base_main.html' %}

{% block extCSS %}
    <link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>
{% endblock %}

{% block extJS %}
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>
     <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
{% endblock %}

{% block indexbody %}
    <!-- MainForm -->
<div id="MainForm">
    <div class="form_boxA">
        <h2>班级信息列表</h2>
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th>序号</th>
                <th>班级名称</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>

            {% for page in pages %}
            <tr>
                <td>{{ page.id }}</td>
                <td>{{ page.g_name | upper}}</td>
                <td>{{ page.g_create_time  }}</td>
                <td><a href="{% url 'app:editorstudent' %}?id={{ page.id }}">编辑</a></td>
            </tr>
            {% endfor %}
        </table>
        <p class="msg">共找到{{ total }}个班级记录</p>
    </div>

    <ul id="PageNum">

        <li><a href="{% url 'app:grade' %}">首页</a></li>
        {% if pages.has_previous %}
        <li><a href="{% url 'app:grade' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>
        {% endif %}
        {% for i in  pages.paginator.page_range %}
        <li><a href="{% url 'app:grade' %}?page_num={{ i }}">{{ i }}</a></li>
        {% endfor %}
        {% if pages.has_next %}
        <li><a href="{% url 'app:grade' %}?page_num={{ pages.next_page_number }}">下一页</a></li>
        {% endif %}
        <li>当前{{ pages.number }}页</li>
        <li><a href="{% url 'app:grade' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
    </ul>

</div>

{% endblock %}

study/Django项目/班级管理后台/templates/head2.html
{% extends 'base_main.html' %}
{% block title %}
    头部-有点
{% endblock %}

{% block extCSS %}
    <link rel="stylesheet" type="text/css" href="/static/css/public.css" />
{% endblock %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="/static/js/public.js"></script>
{% endblock %}

{% block indexbody %}
    <!-- 头部 -->
	<div class="head">
		<div class="headL">
			<img class="headLogo" src="/static/img/logLOGO.png"/>
		</div>
		<div class="headR">
			<span style="color:#FFF"><a href="login.html" target="_blank">【登录】</a></span>
		</div>
	</div>
{% endblock %}


study/Django项目/班级管理后台/templates/index.html
{% extends 'base.html' %}

        {% block title %}
            首页 {{ user.username }}
        {% endblock %}

{% block indexbody %}
    <frameset rows="100,*" cols="*" scrolling="No" framespacing="0"
	frameborder="no" border="0"> <frame src="{% url 'app:head' %}"
	name="headmenu" id="mainFrame" title="mainFrame">
    <!-- 引用头部 -->
<!-- 引用左边和主体部分 -->
    <frameset rows="100*" cols="220,*" scrolling="No"
	framespacing="0" frameborder="no" border="0"> <frame
	src="{% url 'app:left' %}" name="leftmenu" id="mainFrame" title="mainFrame">
<frame src="{% url 'app:grade' %}" name="main" scrolling="yes" noresize="noresize"
	id="rightFrame" title="rightFrame"></frameset></frameset>
    {% endblock %}

study/Django项目/班级管理后台/templates/left.html
{% extends 'base_main.html' %}
{% block title %}
    首页左侧导航
{% endblock %}
{% block extCSS %}
    <link rel="stylesheet" type="text/css" href="/static/css/public.css" />
{% endblock %}

{% block extJS %}
   {{ block.super }}
    <script type="text/javascript" src="/static/js/public.js"></script>
{% endblock%}

{% block indexbody %}
    <!-- 左边节点 -->
	<div class="container">

		<div class="leftsidebar_box">
			<a href="main.html" target="main"><div class="line">
					<img src="/static/img/coin01.png" />&nbsp;&nbsp;首页
				</div></a>

			<dl class="system_log">
                {% for permission in user.role.r_p.all %}
                {% ifequal permission.p_en 'GRADELIST' %}
                    <dt>
                        <img class="icon1" src="/static/img/coin03.png" /><img class="icon2"
                            src="/static/img/coin04.png" /> 班级管理<img class="icon3"
                            src="/static/img/coin19.png" /><img class="icon4"
                            src="/static/img/coin20.png" />
                    </dt>
                    <dd>
                        <img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
                            src="/static/img/coin222.png" /><a class="cks" href="{% url 'app:grade' %}"
                            target="main">班级列表</a><img class="icon5" src="/static/img/coin21.png" />
                    </dd>
                    {% endifequal %}
                    {% endfor %}

                    {% for permission in user.role.r_p.all %}
                    {% ifequal permission.p_en 'GRADEADD' %}
                    <dd>
                        <img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
                            src="/static/img/coin222.png" /><a class="cks" href="{% url 'app:addgrade' %}"
                            target="main">班级添加</a><img class="icon5" src="/static/img/coin21.png" />
                    </dd>
                </dl>
                {% endifequal %}
                {% endfor %}

			<dl class="system_log">
                {% for permission in user.role.r_p.all %}
                    {% ifequal permission.p_en 'STUDENTLIS' %}
				<dt>
					<img class="icon1" src="/static/img/coin03.png" /><img class="icon2"
						src="/static/img/coin04.png" /> 学生管理<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks" href="{% url 'app:student' %}"
						target="main">学生列表</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
                    {% endifequal %}
                {% endfor %}

                {% for permission in user.role.r_p.all %}
                {% ifequal permission.p_en 'STUDENTADD' %}

				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks" href="{% url 'app:addstu' %}"
						target="main">添加学生</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
                {% endifequal %}
                {% endfor %}

			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="/static/img/coinL1.png" /><img class="icon2"
						src="/static/img/coinL2.png" /> 系统管理<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a href="changepwd.html"
						target="main" class="cks">修改密码</a><img class="icon5"
						src="/static/img/coin21.png" />
				</dd>

				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks" href="{% url 'user:logout' %}">退出</a><img
						class="icon5" src="/static/img/coin21.png" />
				</dd>
			</dl>

		</div>

	</div>
{% endblock %}


study/Django项目/班级管理后台/templates/student.html
{% extends 'base_main.html' %}
{% block title %}
    学生列表
{% endblock %}

{% block extCSS %}
    <link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
{#    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>#}
{% endblock %}

{% block extJS %}
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>
    <script>
        function delstu(i) {
            alert(i)
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url:'/app/api/student/' + i + '/',
                type: 'DELETE',
                dataType:'json',
                headers:{'X-CSRFToken':csrf},
                success: function (msg) {
                    location.href ='/app/student/'
                },
                error:function(msg){
                    alert('删除失败')
                },
            });
        }

        $(document).ready(function () {
            $.get('/app/api/student/',function (msg) {
                var html_all = '';
                for (var i =0;i<msg.data.results.length;i+=1){
                    var html ='';
                    html +='<tr>';
                    html +='<td>' + msg.data.results[i].id + '</td>';
                    html +='<td>' +msg.data.results[i].s_name +'</td>';
                    html +='<td>' +msg.data.results[i].g_name +'</td>';
                    html +='<td></td>';
                    html += '<td> <a href="javascript:;" onclick="delstu('+  msg.data.results[i].id +' )">删除</a></td>'
                    html += '</tr>';
                    html_all +=html

                }
                $('#student_list').append(html_all);
            });

        });
        function page() {

        }

    </script>
{% endblock %}

{% block indexbody %}
    <!-- MainForm -->
<div id="MainForm">
    <div class="form_boxA">
        <h2>学生信息列表</h2>
        {% csrf_token %}
        <table cellpadding="0" cellspacing="0" id="student_list">
            <tr>
                <th>序号</th>
                <th>学生名称</th>
                <th>班级</th>
                <th>头像</th>
                <th>操作</th>
            </tr>

        </table>
        <p class="msg">共找到{{ total }}学生记录</p>
    </div>

{#    <ul id="PageNum">#}
{##}
{#        <li><a href="{% url 'app:student' %}">首页</a></li>#}
{#        {% if pages.has_previous %}#}
{#        <li><a href="{% url 'app:student' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>#}
{#        {% endif %}#}
{#        {% for i in pages.paginator.page_range %}#}
{#        <li><a href="{% url 'app:student' %}?page_num={{ i }}">{{ i }}</a></li>#}
{#        {% endfor %}#}
{#        {% if pages.has_next %}#}
{#        <li><a href="{% url 'app:student' %}?page_num={{ pages.next_page_number }}">下一页</a></li>#}
{#        {% endif %}#}
{#        <li><a href="{% url 'app:student' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>#}
{#        <li>当前第{{ pages.number }}页</li>#}
{#    </ul>#}

        <ul id="PageNum">

        <li><a href="next" onclick="page().">首页</a></li>

        <li><a href="http://127.0.0.1:8000/app/api/student/?page=3">上一页</a></li>

        <li><a href=""></a></li>

        <li><a href=" ">下一页</a></li>

        <li><a href="">尾页</a></li>
        <li>当前第 页</li>
    </ul>

</div>
{% endblock %}

study/Django项目/班级管理后台/templates/student2.html
{% extends 'base_main.html' %}
{% block title %}
    学生列表
{% endblock %}

{% block extCSS %}
    <link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
{#    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>#}
{% endblock %}

{% block extJS %}
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>
    <script>
        function delstu(i) {
            alert(i)
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url:'/app/api/student/' + i + '/',
                type: 'DELETE',
                dataType:'json',
                headers:{'X-CSRFToken':csrf},
                success: function (msg) {
                    location.href ='/app/student/'
                },
                error:function(msg){
                    alert('删除失败')
                },
            });
        }

        $(document).ready(function () {
            $.get('/app/api/student/',function () {

            },'json');

        });

    </script>
{% endblock %}

{% block indexbody %}
    <!-- MainForm -->
<div id="MainForm">
    <div class="form_boxA">
        <h2>学生信息列表</h2>
        {% csrf_token %}
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th>序号</th>
                <th>学生名称</th>
                <th>班级</th>
                <th>头像</th>
                <th>操作</th>
            </tr>
            {% for page in pages %}
            <tr>
                <td>{{ page.id }}</td>
                <td>{{ page.s_name }}</td>
                <td>{{ page.g.g_name }}</td>
                <td><img src="/media/{{ page.s_img }}" width='50' height="50"></td>
{#                <td><a href="{% url 'app:delete' %}?id={{ page.id }}">删除</a></td>#}
                <td><a href="javascript:;"onclick="delstu({{ page.id }})">删除</a></td>
            </tr>
            {% endfor %}
        </table>
        <p class="msg">共找到{{ total }}学生记录</p>
    </div>

    <ul id="PageNum">

        <li><a href="{% url 'app:student' %}">首页</a></li>
        {% if pages.has_previous %}
        <li><a href="{% url 'app:student' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>
        {% endif %}
        {% for i in pages.paginator.page_range %}
        <li><a href="{% url 'app:student' %}?page_num={{ i }}">{{ i }}</a></li>
        {% endfor %}
        {% if pages.has_next %}
        <li><a href="{% url 'app:student' %}?page_num={{ pages.next_page_number }}">下一页</a></li>
        {% endif %}
        <li><a href="{% url 'app:student' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
        <li>当前第{{ pages.number }}页</li>
    </ul>

</div>
{% endblock %}